SEED: 100
ENVIRONMENT:
  MAX_EPISODE_STEPS: 150
  CURRICULUM: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['DEPTH_SENSOR']
    HEIGHT: 0.60
    RADIUS: 0.3
  HABITAT_SIM_V0:
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    HFOV: 70
    ORIENTATION: [-0.7, 0.0, 0.0]
    # ORIENTATION: [0, 0, 0]
    # POSITION: [0, 0.69, -0.1778]
    POSITION: [0.0, 1.1, 1.0]
  DEPTH_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    MAX_DEPTH: 10.0
    MIN_DEPTH: 0.3
    HFOV: 70
    ORIENTATION: [0.0, 0.0, 0.0]
    POSITION: [0.0, 0.0, 0.0]
TASK:
  TYPE: MultiNav-v0
  ROBOT: 'Spot'
  ROBOT_URDF: "/coc/testnvme/jtruong33/data/URDF_demo_assets/spot_hybrid_urdf/habitat_spot_urdf/urdf/spot_hybrid.urdf"

  SUCCESS_DISTANCE: 0.425

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  POSSIBLE_ACTIONS: ["VELOCITY_CONTROL"]
  ACTIONS:
    VELOCITY_CONTROL:
      TIME_STEP: 1.0
      CTRL_FREQ: 240.0
      MUST_CALL_STOP: False
      MIN_ABS_HOR_SPEED: 0.035
      MIN_ABS_LIN_SPEED: 0.035
      MIN_ABS_ANG_SPEED: 1.0
      LIN_VEL_RANGE: [-0.50, 0.50]
      HOR_VEL_RANGE: [-0.50, 0.50]
      ANG_VEL_RANGE: [-30.0, 30.0]
      NOISE_MEAN_X: 0.0
      NOISE_MEAN_Y: 0.0
      NOISE_MEAN_T: 0.0
      NOISE_VAR_X: 0.0
      NOISE_VAR_Y: 0.0
      NOISE_VAR_T: 0.0

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'EPISODE_DISTANCE', 'SUCCESS', 'SPL', 'COLLISIONS']
  SUCCESS:
    SUCCESS_DISTANCE: 0.425

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav_hm3d_gibson/pointnav_spot_0.3/{split}/{split}.json.gz
